FROM python:{{python_version}}-bookworm

# Bring uv, our package manager, and pre-commit hooks
ARG UV_VERSION=0.5.26
ARG PRECOMMIT_VERSION=4.1.0
{%- if dynamic_version %}
ARG UV_DYNAMIC_VERSION=0.5.0
{%- endif %}
RUN pip install --no-cache-dir \
    "uv==${UV_VERSION}" \
{%- if dynamic_version %}
    "uv-dynamic-versioning==${UV_DYNAMIC_VERSION}" \
{%- endif %}
    "pre-commit==${PRECOMMIT_VERSION}"

# Workaround critical-level CVEs in Python image
# By forcing just security update (no featureful updates, as part of apt conf)
# Also install make while we're at it, but ignore pinning version warning
# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install --no-install-recommends -y make \
    && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*

COPY . /workdir
WORKDIR /workdir

# Install the local package dependencies (dev-mode)
RUN uv sync
