FROM ghcr.io/astral-sh/uv:python{{python_version}}-bookworm

ARG PRECOMMIT_VERSION=4.2.0
{%- if dynamic_version %}
ARG UV_DYNAMIC_VERSION=0.8.2
{%- endif %}
RUN pip install --no-cache-dir \
{%- if dynamic_version %}
    "uv-dynamic-versioning==${UV_DYNAMIC_VERSION}" \
{%- endif %}
    "pre-commit==${PRECOMMIT_VERSION}"

# Workaround critical-level CVEs in Python image
# By forcing just security update (no featureful updates, as part of apt conf)
# Also install make while we're at it, but ignore pinning version warning
# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install --no-install-recommends -y make \
    && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /workdir

# Changing the default UV_LINK_MODE silences warnings about not being able to
# use hard links since the cache and sync target are on separate file systems.
ENV UV_LINK_MODE=copy

# Install dependencies only, as they don't change often (note bindmount deplist)
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

# Copy the actual project contents into the image
COPY . /workdir

# Sync the project now the code is present
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked
