FROM python:{{ cookiecutter.python_version }}-slim

# Assume the package was built already
COPY dist/ /app/

# Install the package and fetch its dependencies
RUN pip install --no-cache-dir /app/*.whl
