[project]
name = "jb_python_project_skeleton"
version = "2.0.0a29"
description = "A project skeleton for Python projects, using Copier lib"
authors = [{ name = "Jb Doyon", email = "jb@jiby.tech" }]
requires-python = ">=3.13,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["copier>=9.4.1"]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cases",
    "pytest-xdist[psutil]",
    "testcontainers",
    "faker-microservice",
]

[tool.uv.build-backend]
source-include = [
    "template/**",
    "copier.yaml",
    "hooks/**",
    "data/**",
    "CHANGELOG.md",
]

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"

# Make isort work with Black
# Avoids conflicting imports
# As per https://pycqa.github.io/isort/docs/configuration/black_compatibility/#using-a-config-file-such-as-isortcfg
[tool.isort]
profile = "black"
multi_line_output = 3

# Set pytest to record stdout/stderr to junit test result xml
[tool.pytest.ini_options]
junit_logging = "all"
addopts = """-vvvv \
    --color=yes \
    --junit-xml=test_results/results.xml"""
