#!/usr/bin/env bash

# Prepopulates a git repo out of the rendered template with an initial commit+tag
create_git_repository() {
    # If a git repo is already in place
    if [[ -d ".git/" ]];
    then
        exit 0  # No action, exit early
    fi

    # First create empty git repo
    git init --initial-branch main

    # Temporarily set commiter name.
    # Nicely solves problem of "missing git user" in CI by making all
    # template instantiation use a set user name/email combo
    git config --local user.name "Jb Doyon"
    git config --local user.email "jb@jiby.tech"

    # Commit
    git add --all
    git commit \
        --message "Initial commit from cookiecutter template" \
        --message "From python-skeleton repository in Github:" \
        --message "https://github.com/OverkillGuy/python-skeleton" \
        --message "at commit {% gitcommit %}"
    git tag v0.1.0 --message "First releasable artefact, from template"

    # Reset the user config after committing
    git config --unset user.name
    git config --unset user.email
}

delete_unused_files() {
    DELETION_MARKER="DELETE THIS FILE DURING POST_GEN HOOK"

}
create_git_repository
