#!/usr/bin/env bash

# Prepopulates a git repo out of the rendered template with an initial commit

# First create empty git repo
git init

# Temporarily set commiter name.
# Nicely solves problem of "missing git user" in CI by making all
# template instantiation use a set user name/email combo
git config user.name "Jb Doyon"
git config user.email "jb@jiby.tech"

# Commit
git add --all
git commit \
    --message "Initial commit from cookiecutter template" \
    --message "From python-skeleton repository in Github:" \
    --message "https://github.com/OverkillGuy/python-skeleton" \
    --message "at commit {% gitcommit %}"

# Reset the user config after committing
git config --unset user.name
git config --unset user.email
